"""Create operations tables without gen_random_uuid (not available on this PostgreSQL).
UUIDs are generated by Python (uuid.uuid4) at insert time, not by PostgreSQL."""
from sqlalchemy import text
from app.db import engine

with engine.connect() as conn:
    # Check existing
    existing = [r[0] for r in conn.execute(text(
        "SELECT tablename FROM pg_tables WHERE schemaname='public'"
    )).fetchall()]

    if 'operation' not in existing:
        conn.execute(text("""
        CREATE TABLE operation (
            id UUID PRIMARY KEY,
            company_id UUID NOT NULL,
            code_operation VARCHAR(30) UNIQUE NOT NULL,
            intitule VARCHAR(300),
            project_id UUID,
            categorie VARCHAR(30),
            tiers_id UUID,
            contrat_legal_id UUID,
            montant_engage_ht NUMERIC(15,2) DEFAULT 0,
            montant_engage_ttc NUMERIC(15,2) DEFAULT 0,
            montant_rf2 NUMERIC(15,2) DEFAULT 0,
            devise VARCHAR(3) DEFAULT 'DZD',
            statut VARCHAR(20) DEFAULT 'BROUILLON',
            date_debut DATE,
            date_fin_prevue DATE,
            date_fin_reelle DATE,
            responsable_id UUID,
            visa_tresorier BOOLEAN DEFAULT FALSE,
            visa_tresorier_date TIMESTAMPTZ,
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now(),
            created_by UUID,
            is_deleted BOOLEAN DEFAULT FALSE,
            version INTEGER DEFAULT 1
        )"""))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_operation_code ON operation(code_operation)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_operation_statut ON operation(statut)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_operation_company ON operation(company_id)"))
        print("Created: operation")

    if 'operation_budget_agrege' not in existing:
        conn.execute(text("""
        CREATE TABLE operation_budget_agrege (
            id UUID PRIMARY KEY,
            company_id UUID NOT NULL,
            operation_id UUID REFERENCES operation(id),
            source_code VARCHAR(20) NOT NULL,
            source_label VARCHAR(100),
            montant_prevu NUMERIC(15,2) DEFAULT 0,
            montant_reel NUMERIC(15,2) DEFAULT 0,
            methode_calcul VARCHAR(20),
            cle_repartition JSONB,
            derniere_maj TIMESTAMPTZ DEFAULT now(),
            detail_lignes JSONB,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now(),
            created_by UUID,
            is_deleted BOOLEAN DEFAULT FALSE,
            version INTEGER DEFAULT 1
        )"""))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_oba_operation ON operation_budget_agrege(operation_id)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_oba_source ON operation_budget_agrege(source_code)"))
        print("Created: operation_budget_agrege")

    if 'operation_planning_task' not in existing:
        conn.execute(text("""
        CREATE TABLE operation_planning_task (
            id UUID PRIMARY KEY,
            company_id UUID NOT NULL,
            operation_id UUID REFERENCES operation(id),
            parent_task_id UUID,
            jalon_id UUID,
            code_wbs VARCHAR(20),
            intitule VARCHAR(300),
            type_tache VARCHAR(20) DEFAULT 'TACHE',
            date_debut_prevue DATE,
            date_fin_prevue DATE,
            date_debut_reelle DATE,
            date_fin_reelle DATE,
            avancement_pct NUMERIC(5,2) DEFAULT 0,
            avancement_methode VARCHAR(20) DEFAULT 'MANUEL',
            budget_tache NUMERIC(15,2) DEFAULT 0,
            cout_reel_tache NUMERIC(15,2) DEFAULT 0,
            est_critique BOOLEAN DEFAULT FALSE,
            responsable_id UUID,
            statut_tache VARCHAR(20) DEFAULT 'A_FAIRE',
            notes TEXT,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now(),
            created_by UUID,
            is_deleted BOOLEAN DEFAULT FALSE,
            version INTEGER DEFAULT 1
        )"""))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_opt_operation ON operation_planning_task(operation_id)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_opt_parent ON operation_planning_task(parent_task_id)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_opt_critique ON operation_planning_task(est_critique)"))
        print("Created: operation_planning_task")

    if 'operation_dependency' not in existing:
        conn.execute(text("""
        CREATE TABLE operation_dependency (
            id UUID PRIMARY KEY,
            company_id UUID NOT NULL,
            predecesseur_id UUID REFERENCES operation_planning_task(id),
            successeur_id UUID REFERENCES operation_planning_task(id),
            type_dependance VARCHAR(2) DEFAULT 'FD',
            decalage_jours INTEGER DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now(),
            created_by UUID,
            is_deleted BOOLEAN DEFAULT FALSE,
            version INTEGER DEFAULT 1
        )"""))
        print("Created: operation_dependency")

    if 'operation_snapshot' not in existing:
        conn.execute(text("""
        CREATE TABLE operation_snapshot (
            id UUID PRIMARY KEY,
            company_id UUID NOT NULL,
            operation_id UUID REFERENCES operation(id),
            type_snapshot VARCHAR(20),
            date_snapshot DATE,
            donnees_taches JSONB,
            commentaire TEXT,
            created_at TIMESTAMPTZ DEFAULT now(),
            updated_at TIMESTAMPTZ DEFAULT now(),
            created_by UUID,
            is_deleted BOOLEAN DEFAULT FALSE,
            version INTEGER DEFAULT 1
        )"""))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_osn_operation ON operation_snapshot(operation_id)"))
        print("Created: operation_snapshot")

    if 'wbs_template' not in existing:
        conn.execute(text("""
        CREATE TABLE wbs_template (
            id UUID PRIMARY KEY,
            categorie VARCHAR(30),
            name VARCHAR(255),
            tasks JSONB,
            created_at TIMESTAMPTZ DEFAULT now()
        )"""))
        print("Created: wbs_template")

    for tbl in ['ops_it_cost', 'ops_insurance_cost', 'ops_overhead_cost']:
        if tbl not in existing:
            conn.execute(text(f"""
            CREATE TABLE {tbl} (
                id UUID PRIMARY KEY,
                company_id UUID NOT NULL,
                operation_id UUID,
                period VARCHAR(7),
                label VARCHAR(200),
                amount NUMERIC(15,2) DEFAULT 0,
                created_by VARCHAR(100),
                created_at TIMESTAMPTZ DEFAULT now()
            )"""))
            print(f"Created: {tbl}")

    conn.commit()

    # Verify
    ops = [r[0] for r in conn.execute(text(
        "SELECT tablename FROM pg_tables WHERE schemaname='public' AND (tablename LIKE 'operation%' OR tablename LIKE 'wbs%' OR tablename LIKE 'ops_%')"
    )).fetchall()]
    print(f"\nAll operations tables: {ops}")
