"""
GFI v7.0 — CcaMovement: individual CCA transactions.

Every movement requires a justification document — no movement without proof.

Movement types:
  DEPOT: Associate deposits funds into CCA
  RETRAIT: Associate withdraws from CCA (subject to R-003 double rule)
  DISTRIBUTION: Profit distribution credited to CCA
  CFF_DEDUCTION: CFF cost debited from CCA
  DETTE_PERSONNELLE: Personal debt (e.g., Khadidja 18M)
  COMMISSION: Commission income/expense
  REMBOURSEMENT: Debt repayment
  APPEL_FONDS: Capital call response
  TRANSFERT: Inter-CCA transfer

Uses GFIBase (company_id = the entity where the CCA lives).
"""

from sqlalchemy import (
    Column,
    Date,
    ForeignKey,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.models.base import Base, GFIBase


class CcaMovement(GFIBase, Base):
    __tablename__ = "cca_movement"

    # ── Parent CCA account ───────────────────────────────────────────────
    cca_account_id = Column(
        UUID(as_uuid=True),
        ForeignKey("cca_account.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # ── Movement identity ────────────────────────────────────────────────
    movement_date = Column(Date, nullable=False, index=True)
    movement_type = Column(String(30), nullable=False, index=True)
    label = Column(Text, nullable=False)

    # ── Amount (positive = credit to associate, negative = debit) ────────
    amount = Column(Numeric(15, 2), nullable=False)

    # ── Balance after this movement (snapshot) ───────────────────────────
    balance_after = Column(Numeric(15, 2), nullable=False)

    # ── Justification (mandatory) ────────────────────────────────────────
    justification_type = Column(String(40), nullable=False)
    # VIREMENT_CONFIRMATION, CHEQUE_COPY, RECU_ESPECES,
    # PV_DISTRIBUTION, FACTURE, CONTRAT, AUTRE
    justification_ref = Column(String(100), nullable=True)
    justification_path = Column(Text, nullable=True)

    # ── RF classification ────────────────────────────────────────────────
    rf_type = Column(String(3), nullable=True)

    # ── Project link (for CC9/CC10 cost center imputation) ───────────────
    project_id = Column(
        UUID(as_uuid=True),
        ForeignKey("project.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )

    # ── Cost center category ─────────────────────────────────────────────
    cc_category = Column(String(10), nullable=True)
    # CC9 = withdrawals, CC10 = commissions/debts

    # ── Source document link ─────────────────────────────────────────────
    source_document_type = Column(String(60), nullable=True)
    source_document_id = Column(UUID(as_uuid=True), nullable=True)

    # ── Linked journal entry (auto-generated by accounting engine) ───────
    journal_entry_id = Column(
        UUID(as_uuid=True),
        ForeignKey("journal_entry.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ── Metadata ─────────────────────────────────────────────────────────
    metadata_json = Column(JSONB, nullable=True)

    # ── Relationships ────────────────────────────────────────────────────
    cca_account = relationship("CcaAccount", back_populates="movements")
    project = relationship("Project")

    def __repr__(self):
        return (
            f"<CcaMovement {self.movement_type} {self.amount} DA "
            f"on {self.movement_date}>"
        )
