"""
GFI v7.0 — Full Legal Module: litigation, compliance, AI agents.

Extends the existing contract/share transfer system with:
- LegalCase (litigation pipeline with Kanban stages)
- LegalContract (deep legal contract tracking with clause extraction)
- LegalComplianceRule (8 pre-configured Algerian rules)
- LegalComplianceAlert (generated by Agent Conformite)
- LegalContractClause (extracted or manual clauses)
- LegalContractTemplate (6 reusable templates)
- LegalCaseCostLine (per-dossier cost tracking)
- LegalAiTask (queue for 6 juridique AI agents)
"""

from sqlalchemy import (
    Boolean, Column, Date, DateTime, Float, ForeignKey, Integer,
    Numeric, String, Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.models.base import Base, GFIBase


class LegalCase(GFIBase, Base):
    """Dossier juridique: litigation, pre-litigation, compliance."""

    __tablename__ = "legal_case"

    name = Column(String(20), unique=True, nullable=False, index=True)
    case_type = Column(String(30), nullable=False, index=True)
    # PRECONTENTIEUX, CONTENTIEUX_JUDICIAIRE, CONTENTIEUX_RH,
    # CONTENTIEUX_COMMERCIAL, CONFORMITE, ARBITRAGE
    stage = Column(String(40), nullable=False, server_default="'OUVERT'")
    priority = Column(String(20), nullable=False, server_default="'NORMAL'")
    description = Column(Text, nullable=True)

    date_open = Column(Date, nullable=False)
    date_close = Column(Date, nullable=True)
    date_deadline = Column(Date, nullable=True, index=True)

    # ── Parties ──────────────────────────────────────────────────────────
    partner_name = Column(String(255), nullable=True)
    partner_lawyer = Column(String(255), nullable=True)
    company_lawyer = Column(String(255), nullable=True)

    # ── Assignment ───────────────────────────────────────────────────────
    assigned_juriste_id = Column(
        UUID(as_uuid=True), ForeignKey("auth_user.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )
    manager_id = Column(UUID(as_uuid=True), nullable=True)

    # ── Links ────────────────────────────────────────────────────────────
    employee_id = Column(
        UUID(as_uuid=True), ForeignKey("employee.id", ondelete="SET NULL"),
        nullable=True,
    )
    project_id = Column(
        UUID(as_uuid=True), ForeignKey("project.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )

    # ── Financial ────────────────────────────────────────────────────────
    amount_claimed = Column(Numeric(15, 2), nullable=True)
    amount_recovered = Column(Numeric(15, 2), nullable=True)
    cost_total = Column(Numeric(15, 2), nullable=False, server_default="0")

    # ── Result ───────────────────────────────────────────────────────────
    result = Column(String(20), nullable=False, server_default="'EN_COURS'")
    is_confidential = Column(Boolean, nullable=False, server_default="false")

    # ── AI ────────────────────────────────────────────────────────────────
    ai_risk_score = Column(Float, nullable=True)
    ai_summary = Column(Text, nullable=True)
    ai_suggested_actions = Column(JSONB, nullable=True)

    def __repr__(self):
        return f"<LegalCase {self.name} {self.case_type} {self.stage}>"


class LegalContract(GFIBase, Base):
    """Deep legal contract tracking with clause extraction."""

    __tablename__ = "legal_contract"

    name = Column(String(20), unique=True, nullable=False, index=True)
    contract_type = Column(String(30), nullable=False, index=True)
    state = Column(String(20), nullable=False, server_default="'BROUILLON'")

    partner_name = Column(String(255), nullable=True)
    employee_id = Column(
        UUID(as_uuid=True), ForeignKey("employee.id", ondelete="SET NULL"),
        nullable=True,
    )

    date_start = Column(Date, nullable=True)
    date_end = Column(Date, nullable=True, index=True)
    renewal_type = Column(String(20), nullable=True)
    renewal_notice_days = Column(Integer, nullable=True, server_default="60")
    amount = Column(Numeric(15, 2), nullable=True)

    template_id = Column(
        UUID(as_uuid=True), ForeignKey("legal_contract_template.id", ondelete="SET NULL"),
        nullable=True,
    )
    compliance_status = Column(String(20), nullable=False, server_default="'NON_EVALUE'")
    ai_extracted_clauses = Column(JSONB, nullable=True)
    ai_risk_assessment = Column(Text, nullable=True)
    document_url = Column(Text, nullable=True)

    def __repr__(self):
        return f"<LegalContract {self.name} {self.contract_type} {self.state}>"


class LegalComplianceRule(Base):
    """Algerian compliance rules evaluated by Agent Conformite."""

    __tablename__ = "legal_compliance_rule"

    id = Column(UUID(as_uuid=True), primary_key=True,
                server_default=__import__("sqlalchemy").text("gen_random_uuid()"))
    code = Column(String(20), unique=True, nullable=False)
    rule_type = Column(String(20), nullable=False)
    legal_reference = Column(Text, nullable=True)
    description = Column(Text, nullable=False)
    condition_domain = Column(JSONB, nullable=True)
    condition_python = Column(Text, nullable=True)
    ai_prompt = Column(Text, nullable=True)
    severity = Column(String(10), nullable=False)
    action_type = Column(String(20), nullable=False)
    target_model = Column(String(50), nullable=True)
    evaluation_mode = Column(String(20), nullable=False, server_default="'BATCH_DAILY'")
    is_active = Column(Boolean, nullable=False, server_default="true")
    created_at = Column(DateTime(timezone=True), nullable=False,
                        server_default=__import__("sqlalchemy").func.now())

    def __repr__(self):
        return f"<LegalComplianceRule {self.code} {self.severity}>"


class LegalComplianceAlert(GFIBase, Base):
    """Alert generated by Agent Conformite."""

    __tablename__ = "legal_compliance_alert"

    rule_id = Column(
        UUID(as_uuid=True), ForeignKey("legal_compliance_rule.id", ondelete="RESTRICT"),
        nullable=False, index=True,
    )
    rule_code = Column(String(20), nullable=False)
    target_table = Column(String(50), nullable=False)
    target_id = Column(UUID(as_uuid=True), nullable=False)
    severity = Column(String(10), nullable=False)
    # OUVERTE, EN_TRAITEMENT, RESOLUE, IGNOREE
    state = Column(String(20), nullable=False, server_default="'OUVERTE'")
    description = Column(Text, nullable=False)
    recommended_action = Column(Text, nullable=True)
    justification_doc_url = Column(Text, nullable=True)
    assigned_to = Column(UUID(as_uuid=True), nullable=True)
    date_detected = Column(DateTime(timezone=True), nullable=False)
    date_resolved = Column(DateTime(timezone=True), nullable=True)

    def __repr__(self):
        return f"<LegalComplianceAlert {self.rule_code} {self.state}>"


class LegalContractClause(GFIBase, Base):
    """Extracted or manual clauses from a contract."""

    __tablename__ = "legal_contract_clause"

    contract_id = Column(
        UUID(as_uuid=True), ForeignKey("legal_contract.id", ondelete="RESTRICT"),
        nullable=False, index=True,
    )
    name = Column(String(255), nullable=False)
    clause_type = Column(String(30), nullable=True)
    text = Column(Text, nullable=False)
    is_ai_extracted = Column(Boolean, nullable=False, server_default="false")
    risk_level = Column(String(10), nullable=True)
    position_in_doc = Column(Integer, nullable=True)

    def __repr__(self):
        return f"<LegalContractClause {self.name} risk={self.risk_level}>"


class LegalContractTemplate(Base):
    """Reusable contract templates with variable injection."""

    __tablename__ = "legal_contract_template"

    id = Column(UUID(as_uuid=True), primary_key=True,
                server_default=__import__("sqlalchemy").text("gen_random_uuid()"))
    name = Column(String(255), nullable=False)
    contract_type = Column(String(30), nullable=False)
    template_body = Column(Text, nullable=True)
    default_clauses = Column(JSONB, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False,
                        server_default=__import__("sqlalchemy").func.now())

    def __repr__(self):
        return f"<LegalContractTemplate {self.name}>"


class LegalCaseCostLine(GFIBase, Base):
    """Cost tracking per litigation dossier."""

    __tablename__ = "legal_case_cost_line"

    case_id = Column(
        UUID(as_uuid=True), ForeignKey("legal_case.id", ondelete="RESTRICT"),
        nullable=False, index=True,
    )
    description = Column(String(255), nullable=False)
    amount = Column(Numeric(15, 2), nullable=False)
    cost_date = Column(Date, nullable=False)
    cost_type = Column(String(20), nullable=False)
    # HONORAIRES, FRAIS_JUSTICE, EXPERTISE, AUTRE

    def __repr__(self):
        return f"<LegalCaseCostLine {self.cost_type} {self.amount} DA>"


class LegalAiTask(GFIBase, Base):
    """Queue for all juridique AI agent tasks (J1-J6)."""

    __tablename__ = "legal_ai_task"

    agent_type = Column(String(30), nullable=False, index=True)
    # J1_OCR_NLP, J2_CONTRACTUEL, J3_LITIGE, J4_CONFORMITE,
    # J5_COMMUNICATION, J6_ORCHESTRATEUR
    input_data = Column(JSONB, nullable=False)
    output_data = Column(JSONB, nullable=True)
    # PENDING, RUNNING, COMPLETED, FAILED
    state = Column(String(20), nullable=False, server_default="'PENDING'")
    priority = Column(Integer, nullable=False, server_default="5")
    error_log = Column(Text, nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    duration_seconds = Column(Integer, nullable=True)

    # Link to case or contract
    case_id = Column(UUID(as_uuid=True), nullable=True)
    contract_id = Column(UUID(as_uuid=True), nullable=True)

    def __repr__(self):
        return f"<LegalAiTask {self.agent_type} {self.state}>"
