"""GFI v7.0 — Meta-IA tracking tables.

6 tables for AI pipeline traceability.
INVARIANT: auto_deploy = FALSE — never auto-deploy generated code.
"""
import uuid
from sqlalchemy import (
    Column, String, Text, Boolean, Integer, DateTime, Float,
    ForeignKey, JSON, Index, func,
)
from app.database import Base


class MetaObjetMetierDetecte(Base):
    """Business objects detected by AI with confidence scoring."""
    __tablename__ = "meta_objets_metier_detectes"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    document_id = Column(String(36), ForeignKey("documents.id"))
    type_objet = Column(String(100), nullable=False)
    nom_objet = Column(String(300))
    score_confiance = Column(Float, nullable=False)
    donnees_extraites = Column(JSON)
    source_page = Column(Integer)
    source_bbox = Column(JSON)  # bounding box coordinates
    valide_par_humain = Column(Boolean, default=False)
    created_at = Column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("ix_meta_objets_type", "type_objet"),
    )


class MetaRapportLacune(Base):
    """Gap reports generated by AI analysis."""
    __tablename__ = "meta_rapports_lacunes"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    module = Column(String(100), nullable=False)
    description_lacune = Column(Text, nullable=False)
    impact = Column(String(50))  # CRITIQUE, MAJEUR, MINEUR
    resolution_proposee = Column(Text)
    est_resolu = Column(Boolean, default=False)
    date_resolution = Column(DateTime)
    resolu_par = Column(String(36), ForeignKey("users.id"))
    created_at = Column(DateTime, server_default=func.now())


class MetaSpecificationGeneree(Base):
    """Specifications auto-generated by AI."""
    __tablename__ = "meta_specifications_generees"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    module = Column(String(100), nullable=False)
    titre = Column(String(500), nullable=False)
    contenu = Column(Text, nullable=False)
    version = Column(Integer, default=1)
    validation_humaine = Column(Boolean, default=False)
    valide_par = Column(String(36), ForeignKey("users.id"))
    date_validation = Column(DateTime)
    created_at = Column(DateTime, server_default=func.now())


class MetaCodeGenere(Base):
    """Code generated by AI — INVARIANT: auto_deploy MUST be FALSE."""
    __tablename__ = "meta_code_genere"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    module = Column(String(100), nullable=False)
    fichier_cible = Column(String(500))
    langage = Column(String(50), default="python")
    contenu_code = Column(Text, nullable=False)
    auto_deploy = Column(Boolean, default=False, nullable=False)  # INVARIANT: always FALSE
    revue_par = Column(String(36), ForeignKey("users.id"))
    date_revue = Column(DateTime)
    est_approuve = Column(Boolean, default=False)
    created_at = Column(DateTime, server_default=func.now())


class MetaResultatTest(Base):
    """Test results from AI-generated or kill tests."""
    __tablename__ = "meta_resultats_tests"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    test_name = Column(String(200), nullable=False)
    test_type = Column(String(50))  # KILL_TEST, UNIT, INTEGRATION, SANITY
    resultat = Column(String(20), nullable=False)  # PASS, FAIL, SKIP, ERROR
    duree_ms = Column(Integer)
    details = Column(JSON)
    couverture_pct = Column(Float)
    created_at = Column(DateTime, server_default=func.now())

    __table_args__ = (
        Index("ix_meta_test_type", "test_type"),
    )


class MetaFeedbackApprentissage(Base):
    """Feedback loop for AI learning."""
    __tablename__ = "meta_feedback_apprentissage"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    objet_id = Column(String(36))  # references any meta table
    type_feedback = Column(String(50))  # CORRECTION, VALIDATION, REJET
    commentaire = Column(Text)
    score_avant = Column(Float)
    score_apres = Column(Float)
    utilisateur_id = Column(String(36), ForeignKey("users.id"))
    created_at = Column(DateTime, server_default=func.now())
